version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.5
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.13.8
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.5
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.12.10
    - 7.13.8
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
  - dependency-name: eslint
    versions:
    - 6.5.0
